### ISSUE TITLE
One ColdFusion plugin - Open Source organization

### ISSUE THREAD

**Issue by ilich** [KamasamaK/vscode-cfml#1]
Hello @KamasamaK. 

I have checked the plugin, and it looks great. As you know, I also started to work on similar plugin. What do you think about joining our efforts by creating an Open Source organization on GitHub and working together on one CFML plugin for VS Code? I think it will be easier for the community to contribute in this case because there will be just one point of contact.

If you like the idea, what is the best way to contact you?

Sincerely,
Ilya

**Comment by KamasamaK** [comment]
Hi @ilich,

I've sent you an email.

**Comment by richardherbert** [comment]
That would be a great idea guys!

Have you seen...

https://github.com/teamcfadvance

**Comment by sosensible** [comment]
I am for this also.

**Comment by chippinkston** [comment]
Just wanted to check if there was any sort of update on this.  Currently planning on testing out this extension.

**Comment by arthurblake** [comment]
It seems like this extension has more features than the one by @ilich - But neither extension has been updated in ~4 months. I would like to start working on some pull requests to improve the plugin. Is any effort being made to unify on one plugin? Is this plugin going to continue to be improved?

**Comment by KamasamaK** [comment]
It seems that @ilich is unable to further develop an extension due to lack of time -- [Source](https://github.com/ilich/vscode-coldfusion/blob/b700b3354ed8a1f9716518dc815bf641a66f64bb/README.md#project-discontinued). I am still open to others contributing and possibly making an organization if there is interest from more contributors.

**Comment by WebVeteran** [comment]
I wish there was a way to create a bounty in github.  99% of my work is ColdFusion. I would definitely pay for a plugin that works and I wouldn't care if it were free for others.
The current CF extnsions for vscode are not usable in a production capacity.

**Comment by elpete** [comment]
@WebVeteran If you have specific issues please open issues here for them (or better yet, pull requests). Mentioning a bounty amount would probably help as well. I happen to use this plugin all day for production use and it works great for me, so “not usable in a production capacity” isn’t very helpful feedback.

**Comment by WebVeteran** [comment]
> @WebVeteran If you have specific issues please open issues here for them (or better yet, pull requests). [...] “not usable in a production capacity” isn’t very helpful feedback.

Fair enough. Give me a week to compile a list.

As for the amount - I'd be willing to pitch in a few hundred. Probably not enough to fully compensate the effort. But It wouldn't be spec work just for me.
