### ISSUE TITLE
Syntax highlight issue in closures

### ISSUE THREAD

**Issue by ryphill** [KamasamaK/vscode-cfml#12]
Using a try catch statement in a closure seems to cause the syntax highlighting to become a bit wonky. A code example that will cause it is:
```cfm
<cfscript>
data = [1, 2, 3, 4];
data.each(function(item, index) {
	var errors = [];
	var flag = false;

	try {
		flag = true;
	} catch (any e) {
		flag = false;
	}

	if (flag) {
		error.append({'index': index});
	}
});
</cfscript>
```
Example of how it looks for me:
![cfm_highlight_issue](https://user-images.githubusercontent.com/2074559/38151977-6f7f916a-3433-11e8-8765-e22779e69257.png)

I'm using vscode-cfml version 0.3.1 and vscode version 1.21.1

**Comment by KamasamaK** [comment]
This is fixed in 0.4.0
