### ISSUE TITLE
CF doc improvements

### ISSUE THREAD

**Issue by arthurblake** [KamasamaK/vscode-cfml#14]
It looks like you may be planning for some of these ideas in the future... but here are my thoughts:

I love the integrated hover documentation, but I can think of a few improvements that would really help my workflow.

I find myself wanting to pull up the help in the browser directly more often then not. The link at the bottom of the help popup is kind of small and hard to click on and I have to scroll all the way down if the help content is large. I wish the link was at the top instead.  Also it would be nice if I could set up a key mapping to go straight to the browser HTML help (maybe there is a way to configure this that I don't know about?)

Also, I would like to be able to jump directly to an engine specific help from vscode (rather than only being able to go into cfdocs help) yet without losing the ability to also go to the cfdocs help or some other engine help. Having something right in the hover that looks like the little icons in cfdoc that go straight to the engine specific help, but where I can jump directly to it from vscode, rather than having to first go to the cfdoc site and then branch off from there:

![screen shot 2018-06-06 at 5 47 31 pm](https://user-images.githubusercontent.com/247797/41066942-b8c49a38-69b1-11e8-87da-f417a2bd9d2e.png)

I can visualize how to make this work in a very configurable and user friendly way.
I may try to work up a PR if you are open to some of these ideas...

**Comment by KamasamaK** [comment]
I am fine with moving the link under the description and above the parameters. When I initially created it, I was trying to replicate the one from the Sublime Text plugin as best I could.

I will create two commands. One of the commands will bring you to the CFDocs page and the other will bring you to the engine docs page based on your `cfml.engine.name` setting. You will have to place your text cursor within the tag or function before running the command. VS Code will allow you to create your own key binding for commands.

**Comment by arthurblake** [comment]
What about having the little links to each engine (like in the my screen shot?)
In my opinion there is no sense in emulating the Sublime plugin exactly if there are opportunities to make it better.

**Comment by arthurblake** [comment]
Also I can see for having a direct command to go to each engine help discretely may be useful as well (no matter what the` cfml.engine.name` setting is.)

**Comment by KamasamaK** [comment]
In v0.5.0, I've added icons for each engine that act as links to their respective documentation pages.
