### ISSUE TITLE
cfm files 

### ISSUE THREAD

**Issue by Xcreen** [KamasamaK/vscode-cfml#15]
First of all, thanks for this awesome extension!!!
Tags and Functions working fine in cfc files, but on cfm files its not working.  (no suggestions etc.)
Maybe i have some miss configuration or something?

**Comment by KamasamaK** [comment]
Can you please provide more information? Does it work in _every_ cfc file but _no_ cfm files? The extension should work for cfm files without any configuration change and I am unaware of what specifically might be causing this issue.

**Comment by pldray** [comment]
I found it didn't work when using an sFTP connection. Local files or mapped drives are okay.

**Comment by KamasamaK** [comment]
@pldray Please open a new issue for that. This is due to #13. Also, please provide what extension you're using for sFTP so it can be tested.

**Comment by KamasamaK** [comment]
Closing due to lack of feedback
