### ISSUE TITLE
Symbols Navigation

### ISSUE THREAD

**Issue by devalnor** [KamasamaK/vscode-cfml#20]
It will be great to have symbols navigation like on Sublime

I saw that you have symbol search. I tried `cmd-shirt-0` but it's doing nothing on my Mac.
A `cmd-D` who list all the current file symboles will be great feature like on Sublime.

Thanks for this extension.
Mx

**Comment by KamasamaK** [comment]
According to the [keyboard shortcuts for macOS](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf), the default for "Go to Symbol..." is `Cmd`+`Shift`+`O` (note this is not `0`) -- verify that something is not overriding this shortcut. Even if there are no document symbols for that file, it will at least pop up something to say as much.

This is something built into VS Code and not contributed by this extension. This extension contributes the document symbols themselves, which allows for them to be used with things like VS Code's "Go to Symbol...", outline view, and breadcrumbs view.

**Comment by devalnor** [comment]
Thanks @KamasamaK, I fell stupid with my `0` key. 
Hopefully `code marking` it, help to understand my mistake.
