### ISSUE TITLE
html autocomplete is not working in cfml files

### ISSUE THREAD

**Issue by orellabac** [KamasamaK/vscode-cfml#22]
The built in html support in cfml files does not work.
Also cfml autocomplete should put the cursor inside the tags

**Comment by KrunchMuffin** [comment]
I am having the issue with HTML as well. Uninstalled and reinstalled.
Also, other extensions that used to work like bootstrap and fontawesome tag completion are no longer working either. Assuming some sort of relation of CFML to HTML is missing?

**Comment by KrunchMuffin** [comment]
hmmm...just read this

> There is no embedded language support, which means that you will not get HTML/CSS/JS/SQL assistance within CFML files. You will still get syntax highlighting and you can use user snippets and Emmet to supplement somewhat.

I could have sworn this worked before. Is this a huge hurdle?

**Comment by KamasamaK** [comment]
There was no built-in HTML completion for CFML files before v0.5.0. HTML tag and attribution completion should now be working.

Can you explain what you mean regarding the cursor inside the tags?

**Comment by KamasamaK** [comment]
That would be "inside the quotes", which it does now. But there were no quotes on completion prior to v0.5.0.

**Comment by KrunchMuffin** [comment]
ok, cool. Not sure then what he meant.
