### ISSUE TITLE
HTML Element completion and in/out-dent not working properly

### ISSUE THREAD

**Issue by WebVeteran** [KamasamaK/vscode-cfml#23]
Tag completions and auto indent and outdent don't work properly.

I've quadruple checked all the settings:
- HTML
- Cfml
- Auto-close-tag

Still the functionality is not what is to be expected. I used simple HTML tags here to demnstrate - in both CFM and HTML files. The HTML file works correctly.

See attached zipped MP4.

[tags.mp4.zip](https://github.com/KamasamaK/vscode-cfml/files/2470000/tags.mp4.zip)

**Comment by KamasamaK** [comment]
HTML settings would not affect this if you have the language for the file is set to CFML. Regarding your video, it was very helpful. Here are my responses:

1. Adding a tag should 
a. Auto-close on `<\`: Auto-closing is exclusively handled by the extension `auto-close-tag`. The only thing this extension does is modify the configuration for you to exclude certain tags. I believe the setting for this is `"auto-close-tag.SublimeText3Mode": true` as indicated in its README. If you are having an issue with that setting, you should open an issue in that extension's repository.
b. Auto-indent the next line when hitting return: It should work like this in v0.5.0+
2. Modifying a tag should
a. Not duplicate the tag. Again, this is handled by the `auto-close-tag` extension.
b. Auto-indent the next line when hitting return: See 1.b.
3. Re-indent should not indent `head` and `body`: I'm not sure how that command works. Also, I don't know why they would not be indented. This does not seem like something worth looking into.

**Comment by WebVeteran** [comment]
1a. It works.
1b. It works.

2a. It works.
2b. It works, but there is a related issues. I'll see if it's posted already and if not will create.

3. Certainly not a deal breaker. But it's a nice option - saves you two indentations of horizontal space when re-indenting.

Again - awesome work. Thank you. I'll have to now consider moving form ST3 to VSC!
