### ISSUE TITLE
CFMLCompletionItemProvidor Error

### ISSUE THREAD

**Issue by maverck** [KamasamaK/vscode-cfml#27]
[2019-01-14 21:56:04.125] [exthost] [error] TypeError: Cannot read property 'uri' of undefined
	at CFMLCompletionItemProvider.provideCompletionItems (/home/maverck/.vscode/extensions/kamasamak.vscode-cfml-0.5.0/out/features/completionItemProvider.js:284:159)  
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:561:127  
	at t.asThenable (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:141:941)  
  
occurs when i try add a dot after a variable containing a component  
doesn't provide function/variable completion suggestions.

**Comment by maverck** [comment]
I narrowed the problem down to interfaces.
I had a few interfaces that defined some functions.

The simplest one is this

`interface name="IJsonConverter" {

  string function getJsonString();
  void function loadJson(required array json);
  void function loadJsonString(required string jsonString);

}`

If i remove the functions and just have it as an empty interface. i no longer get the error and completions work.
Removing the interface entirely also fixes the problem

**Comment by KamasamaK** [comment]
Thanks for providing more detail. Can you please be specific how the interface is causing the issue? What relation does the interface have with the file that is having the issue? Or is the issue with every file if the interface exists in the workspace?

**Comment by KamasamaK** [comment]
Please see if v0.5.1 fixes your issue.

**Comment by msp1kpj** [comment]
I am still having the same issues on v0.5.1.
![image](https://user-images.githubusercontent.com/7109246/51392166-d5f08780-1af9-11e9-8bc3-2cec09ad1ea2.png)

**Comment by KamasamaK** [comment]
@msp1kpj Would you be able to provide a sample file in which this error occurs? I could just make it not error there, but if I know why it is failing I could probably make a smarter fix.

**Comment by maverck** [comment]
Appears to be fixed for me. Thank you.  
  
At first i didn't think it was fixed but then i noticed my workspace mappings were gone.  
I assume i did this when i was testing and the extension couldn't have reset these.
