### ISSUE TITLE
cffunction Syntax Highlighting Issue

### ISSUE THREAD

**Issue by StayFrosty54** [KamasamaK/vscode-cfml#29]
Hi, 

cffunction provides a "meta.function.cfml" scope to the angle brackets surrounding it which allows me customize their highlighting. Unfortunately the same scope is missing in the closing tag. 

![image](https://user-images.githubusercontent.com/11181749/51471992-84096500-1d78-11e9-90cd-0e59c63bf543.png)

Would it be possible to also add said scope to the closing tag punctuation (angle brackets and backslash)?

The same issue is also present on cfcomponent.

**Comment by KamasamaK** [comment]
I've made this change for v0.5.3
