### ISSUE TITLE
Identifying custom tags in code and syntax highlighting

### ISSUE THREAD

**Issue by shakeelosmani** [KamasamaK/vscode-cfml#4]
Sublime Text handles this well with it's CFML plugin. Let me show a code snippet below:
![image](https://user-images.githubusercontent.com/9120484/33490997-e5b7fc42-d686-11e7-9c00-c807f59e0398.png)

For example in my code base I have a custom tag called cf_javascript as shown above. Inside which I write plain JavaScript but the editor does not recognize it at all and I do not get any syntax highlighting. Off course when I am writing new code easy solution has been to wrap it in script tag and then change it at the end. But reading old code is painful. Is there an easy fix for this.

**Comment by KamasamaK** [comment]
I've just tested [sublimetext-cfml](https://github.com/jcberquist/sublimetext-cfml) and found minimal difference between the syntax highlighting.

**sublimetext-cfml**
![sublimetext-cfml_cfjavascript_test](https://user-images.githubusercontent.com/22951521/34495765-99e7e6fe-efc4-11e7-9a7a-31f01a3af16f.png)

**vscode-cfml**
![vscode-cfml_cfjavascript_test](https://user-images.githubusercontent.com/22951521/34495771-a33da770-efc4-11e7-956c-2597a27a852a.png)

The main difference I notice is that the CSS within the `style` attribute value is highlighted as CSS, which is an enhancement I would be open to implementing. That is independent from this issue, though.

I'm not sure what you are expecting here. The JavaScript syntax is only active within `<script>` tags, so both plugins are just using HTML syntax highlighting. I have no good idea how the syntax would identify the contents of custom tags, and I do not think guessing based on the custom tag name is appropriate. The syntax is mostly based on the language specs, and I would rather not take too many liberties with that unless there is a wide use case.

I would not call it an "easy fix", but you can modify the syntax file on your local machine -- in Windows, that's `{User}\.vscode\extensions\KamasamaK.vscode-cfml-M.m.p\syntaxes\cfml.tmLanguage.json`. Just be aware that it will be overwritten each time the extension is updated.
