### ISSUE TITLE
Add CommandBox Scripts Explorer Support

### ISSUE THREAD

**Issue by lmajano** [KamasamaK/vscode-cfml#42]
Can we add CommandBox Scripts Explorer Support like npm scripts?

NPM Scripts Explorer visible by default
Previously, you had to enable the setting npm.enableScriptExplorer to make the NPM Scripts Explorer visible and this was difficult to discover. The NPM Scripts Explorer is now shown collapsed in the File Explorer, when there is a package.json file at the root of the workspace.

NPM Scripts Explorer collapsed

When you have no package.json at the root in your workspace, you can still use the setting to enable the NPM Scripts Explorer. If you want to hide the explorer, you can right-click on its title and select Hide from the context menu.

**Comment by lmajano** [comment]
For some reason I can't upload files, maybe github is broken!

**Comment by KamasamaK** [comment]
What are your thoughts on a dedicated CommandBox extension? I would prefer if this could stay dedicated to being a language extension. I think some other features could be added as well to match what the `npm` extension provides, such as ForgeBox integration into dependencies.

**Comment by lmajano** [comment]
I like it: https://github.com/Ortus-Solutions/vscode-commandbox

Would you like to lead it :)

**Comment by KamasamaK** [comment]
Sure. When I get some time, I will see what I can do.
