### ISSUE TITLE
Syntax highlighting issues with embeded CSS in .cfm file

### ISSUE THREAD

**Issue by erobertson42** [KamasamaK/vscode-cfml#45]
I've come across a couple syntax highlighting issues regarding CSS within `<style>` tags in `.cfm` files.

1. There is no syntax highlighting being done to style definitions within a `@media` query.
2. Using a `@media` query breaks syntax highlighting in the rest of the CSS under it.
3. Commenting out anything within the `@media` query that includes the first line breaks Javascript syntax highlighting below.  Namely, that the `#` symbol in the query selector is now treated as if it's within a `<cfoutput>` tag and needs to be escaped (`##`).

Here is a gif with an example:
![CFML gif](https://i.imgur.com/dZegi50.gif)

This does not occur with CSS before the `@media` query, or with the exact same code in an `.html` file.

**Comment by KamasamaK** [comment]
Embedded CSS syntax has been improved to accommodate for `@media` queries in v0.5.4. Can you verify that this is now fixed?

**Comment by erobertson42** [comment]
Thank you.  Unfortunately I am currently out of the office on vacation until Jan 24.  I will be sure to take a look when I get back.

**Comment by erobertson42** [comment]
Seems to behave as expected now.  Thanks again!
