### ISSUE TITLE
also publish to open-vsx.org

### ISSUE THREAD

**Issue by futwick** [KamasamaK/vscode-cfml#53]
Hi, is there any chance you could also publish this extension to https://open-vsx.org/ so that it can be installed in VSCodium?

**Comment by constantin-mike** [comment]
Yes please! And CFLint if possible. Thank you! Great extension but sadly ATM it cannot be used with VSCodium.

**Comment by KamasamaK** [comment]
This extension is now published at https://open-vsx.org/extension/KamasamaK/vscode-cfml
