### ISSUE TITLE
TestBox Spec Outline

### ISSUE THREAD

**Issue by elpete** [KamasamaK/vscode-cfml#6]
There's a really nifty feature in Sublime Text called the TestBox Spec Outline.  I'd love this in VS Code.

https://github.com/jcberquist/sublimetext-cfml/commit/322722263b110ec1add2b851b7e15d15a3ac1d8d

**Comment by elpete** [comment]
cc @lmajano

**Comment by lmajano** [comment]
Any udpates on this?

**Comment by lmajano** [comment]
@elpete we should close this as we implemented it in the TestBox extension right?
