### ISSUE TITLE
Publish to OpenVSX

### ISSUE THREAD

**Issue by filiptronicek** [KamasamaK/vscode-cfml#73]
Hi @KamasamaK!

Unfortunately, Microsoft prohibits the usage of the MS Extension Marketplace by any other non-microsoft products. Because of this, we kindly ask you to take the ownership of your namespace in OpenVSX and publish there as well.

OpenVSX is a vendor neutral alternative to the MS Marketplace used by all other derivatives of VS Code like Gitpod, OpenVSCode, VSCodium, Theia based IDEs, and so on.

The docs for publishing the extension are here: [eclipse/openvsx/wiki/Publishing-Extensions](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). Technically this should be straightforward. You get a token and call `ovsx publish` with it. For example, this is how RedHat publishes their java extension: https://github.com/redhat-developer/vscode-java/blob/5d4f8d58b8e919534800ca7bc41e8513c288f573/Jenkinsfile#L78-L82.

Please do let me know if you are open to receive a PR contributing a release GitHub Action both to MS marketplace and OpenVSX. I'd love to help out! 

PS. It would also be great if we could publish https://github.com/KamasamaK/vscode-cflint to OpenVSX as well.

**Comment by KamasamaK** [comment]
I haven't used GitHub Actions before, but I would be open to using them to publish. If possible, it should be when I create a new Release. I haven't created any for this project yet, but I should and will. I assume the tokens would simply be added to Repository secrets.

**Comment by filiptronicek** [comment]
@KamasamaK awesome, happy that you're open to create a process for this!

> I haven't used GitHub Actions before, but I would be open to using them to publish. If possible, it should be when I create a new Release.

In addition to triggering after a release on GitHub releases, we could also make a manually triggered workflow that would create the release for you, also with a release asset containing the packaged extension.

> I assume the tokens would simply be added to Repository secrets. 

Completely right.

**Comment by KamasamaK** [comment]
Sure, that would be great. I wasn't familiar with manually triggered workflows. I assume the release asset would also honor the `.vscodeignore`.

**Comment by filiptronicek** [comment]
@KamasamaK I am currently working on this in my fork (https://github.com/filiptronicek/vscode-cfml), but when packaging up the extension, I get many typescript errors, because `tsc` checks the projects dependencies for errors as well. Did you have to tackle this in the past, or is this new to you?

**Comment by KamasamaK** [comment]
@filiptronicek I've updated some dependencies and made some other minor tweaks. Sync your fork and see if that fixes it.

**Comment by filiptronicek** [comment]
@KamasamaK thanks a lot for the fixes! I just created #74
