### ISSUE TITLE
snippets not working inside tags.

### ISSUE THREAD

**Issue by arthurblake** [KamasamaK/vscode-cfml#8]
I cannot get a snippet to work when I'm inside a tag. For example I have a snippet set up to enter a cfqueryparam tag, but I can only seem to invoke it when I'm outside of a cfquery tag. Which totally defeats the purpose of the snippet. ..

**Comment by KamasamaK** [comment]
I made a possibly controversial decision to set some of the embedded language IDs accordingly within those tags (e.g. css, javascript, and sql). If your snippet only targets `cfml` then it won't activate in a `<cfquery>` which has `sql` active. As far as I am aware, you cannot have 2 language IDs active at the same time, so I chose the embedded one. It may not be ideal, but as of VS Code 1.20, you can have snippets target multiple language IDs. Add a [global snippet](https://code.visualstudio.com/updates/v1_20#_global-snippets) and provide the scope `cfml,sql` and it should work.

**Comment by arthurblake** [comment]
I am new to both vscode and vscode-cfml. Thank you for the commentary and suggested work-around. It is working well for me.

**Comment by arthurblake** [comment]
By the way. Thanks for your plugin. It's great!
