### ISSUE TITLE
Enhancement Request: Support CFScript Files

### ISSUE THREAD

**Issue by isapir** [KamasamaK/vscode-cfml#87]
Lucee supports CFScript files with the extension `*.cfs`.

That allows you to write CFScript code without the `<cfscript>` tag, e.g. a valid file can be:

```
// filename: time.cfs

echo(now());
```

ATM if I don't wrap that CFScript code with the `<cfscript>` tag I do not get the syntax highlighting, making it very difficult to use those files.  It would be great if the extension would support them.

**Comment by garethedwards-tass** [comment]
Can't you just write cfc's in script?

<img width="458" alt="image" src="https://github.com/KamasamaK/vscode-cfml/assets/113149910/54bd275e-2166-4bc1-94ea-780d3793e412">

**Comment by isapir** [comment]
@garethedwards-tass You can, but I want it to work without the `component { }` outer keyword

**Comment by isapir** [comment]
I wonder if it can be as simple as adding a ".cfs" file extension check to `docIsScript` at https://github.com/KamasamaK/vscode-cfml/blob/4643e0f1c141f5077094a12f7ed67fc06cae3808/src/utils/documentUtil.ts#L44

**Comment by ghedwards** [comment]
I don't maintain this project so I can't push any changes here, but I can at https://github.com/cfmleditor/cfmleditor , which is basically a fork of this project. Can you point me at documentation for this file type and I'll do my best to get it included

**Comment by isapir** [comment]
@ghedwards It was available before Lucee 6, but now it's official:
https://dev.lucee.org/t/what-is-new-in-lucee-6-part-2/13248#cfs-templates-12

**Comment by isapir** [comment]
Thanks @ghedwards - I installed https://marketplace.visualstudio.com/items?itemName=CFMLEditor.cfmleditor instead of the one in this repo.  Great job!
