### ISSUE TITLE
Go to declaration / get CFC name

### ISSUE THREAD

**Issue by arthurblake** [KamasamaK/vscode-cfml#9]
I would like to be able to go to the declaration of a CFC.
For example, with this code:

`<cfcomponent extends="abc.def.MyCfc">`

or this code

`<cfset local.obj = CreateObject('component', 'demo.components.util.MyUtil')>`

I should be able to right click on the string (in the above examples, "abc.def.MyCfc" or 'demo.components.util.MyUtil') for the CFC name and select "Go to definition" (F12 on windows) to go right to the source for the CFC if it's in the workspace.

To make this work, I might need to define some mappings for where my components are located, or if it was really slick, it could auto-detect (via best guess) if there is a matching file with a matching path/ subpath in the workspace.

Even more useful would be it could just automagically detect any string in any CFC/CFML context that looks like a dot separated pattern that happens to match a path+CFC combination that exists, and allow the hop from that string to the source file.

Conversely, if I am in a CFC module, I'd like to copy the CFC name for the current module to the clipboard so I can paste it for use elsewhere.

I have some external macros set up to do all of these things, that I used with another editor (and have not yet bothered to figure out how to set up with vscode), but it sure would be nice if this functionality were built into the extension. I would think it's a common need.

**Comment by KamasamaK** [comment]
The requested functionality of providing definitions for extends and object creation (and more) already exists, but it currently only resolves the paths relative to the invoking file or the workspace folder root, which is assumed to be the webroot. The mappings is what is missing and planned. It would likely be a setting which I would like to model after the CFConfig format.

The ability to create a dotted path in the clipboard should be a separate issue.

**Comment by lmajano** [comment]
VSCode already leverages the `.vscode/settings.json` why not use that?  I would love to be able to do this, CFBuilder does this and it is a huge help. This way you can map project mappings.

**Comment by KamasamaK** [comment]
Mappings have been added in v0.4.0. Please verify if this satisfies your request.

**Comment by lmajano** [comment]
I see in the readme that the directory path for the mapping is absolute. Is there a way to do it relative to project root?

**Comment by KamasamaK** [comment]
@lmajano Yes, you can also do the following
```json
"cfml.mappings": [
  {
    "logicalPath": "/model",
    "directoryPath": "/app/model",
    "isPhysicalDirectoryPath": false
  }
]
```

**Comment by arthurblake** [comment]
Hey thanks for working on this (I just cloned the project and was trying to figure out how to implement it myself!) Seems to work OK. One problem I have though is that the go to definition usage seems to be limited. It should work from any string.  I have code that passes CFC names around to alternate loaders. For example:

`request.cfcCache.get('a.b.c.Def') `

In the above example, I should be able to place the cursor on the string 'a.b.c.Def' and hit F12 or right click and select Go to Definition and have it work the same. But it only works from the obvious places (like CreateObject or cfcomponent extends.)

I cannot think of a good reason to not allow this to work from any string (and it would make it 1000x more useful for my codebases.) Can you think of a good reason to not allow this?

I know this is getting a little off topic from the original reported issue, and I can open a new issue if you desire.

**Comment by arthurblake** [comment]
Also, can you document the isPhysicalDirectoryPath setting in the vs code extension splash?  Took me some fiddling to figure out how to get the mappings to work properly and more documentation will always be appreciated!

**Comment by KamasamaK** [comment]
I have added another mappings example to the readme. The one on the extensions page will only refresh when a new version is pushed.

When you say definitions only work from the obvious places, I take that to mean from the places where it makes sense. I don't like the idea of taking contents of strings and arbitrarily trying to make assumptions on their semantics.

**Comment by arthurblake** [comment]
The "Go to Declaration" option is available everywhere the cursor is, but it only works in some select places. If it can match something reasonably well on a best effort basis, it would make the tool all the more powerful. Especially in code bases where a lot of loose binding is going on and CFC names are passed around as strings a lot. It's easy enough to do a pattern check of dot separated names and then see if the corresponding file exists within the mappings and only do the jump if it's found. In other words, I only see upside to this feature, no downside. After all, what would be the intention of a user even trying to use the go to declaration on a literal string in the first place? What is the down side (other than not being "proper" in some way?)

**Comment by arthurblake** [comment]
The idea is not a whole lot different from URLs that can appear in strings and comments. Vscode recognizes them as URL patterns and lets you open them in a browser with Ctrl-Click. A very handy feature. If a String (anywhere in code or comments) can be recognized as a pattern that matches to a an actual CFC somewhere in the workspace, why not allow a hop to it? At any rate it's certainly something that would improve my velocity a lot with some of my codebases.

**Comment by KamasamaK** [comment]
The URL detection is a bit different because it only matches what are clearly URLs, so I wouldn't describe it as arbitrary or ambiguous. For example, it will match `https://www.google.com` but will not even match `www.google.com`. If there were no ambiguity or some kind of context clue that would indicate it as a component path then I would have no problem with it.

**Comment by arthurblake** [comment]
Yeah you have a point. It's ambiguous with java class names for example.  In my mind, the ambiguity is resolved because if it finds a file, that's good enough (given that there is no chance of matching anything else anyway, so it's better than not having it at all.) If you don't think this feature would be worthy, maybe I can build a really small extension for VS code to do just the needed behavior for me.
